In [1]:
#### Import python libraries
import psycopg2

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\hp\Desktop\Datasets\sales.csv")

#### Extract

In [4]:
def Extract():
    df = pd.read_csv(r"C:\Users\hp\Desktop\Datasets\sales.csv")
    return df

#### Transform

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
def Transform():
    df.drop('ADDRESSLINE2',axis = 1, inplace = True)
    return df

In [7]:
df[df['STATE'].isnull()].head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
6,10180,29,86.13,9,2497.77,11/11/2003 0:00,Shipped,4,11,2003,...,"184, chausse de Tournai",NaN,Lille,NaN,59000,France,EMEA,Rance,Martine,Small
7,10188,48,100.00,1,5512.32,11/18/2003 0:00,Shipped,4,11,2003,...,"Drammen 121, PR 744 Sentrum",NaN,Bergen,NaN,N 5804,Norway,EMEA,Oeztan,Veysel,Medium
9,10211,41,100.00,14,4708.44,1/15/2004 0:00,Shipped,1,1,2004,...,"25, rue Lauriston",NaN,Paris,NaN,75016,France,EMEA,Perrier,Dominique,Medium

In [8]:
df[df['STATE'].notnull()].head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
5,10168,36,96.66,1,3479.76,10/28/2003 0:00,Shipped,4,10,2003,...,9408 Furth Circle,NaN,Burlingame,CA,94217,USA,NaN,Hirano,Juri,Medium
8,10201,22,98.57,2,2168.54,12/1/2003 0:00,Shipped,4,12,2003,...,5557 North Pendale Street,NaN,San Francisco,CA,NaN,USA,NaN,Murphy,Julie,Small

In [9]:
df.groupby('COUNTRY')['STATE'].apply(lambda x: x.isnull().mean())

COUNTRY
Australia      0.000000
Austria        1.000000
Belgium        1.000000
Canada         0.000000
Denmark        1.000000
Finland        1.000000
France         1.000000
Germany        1.000000
Ireland        1.000000
Italy          1.000000
Japan          0.000000
Norway         1.000000
Philippines    1.000000
Singapore      1.000000
Spain          1.000000
Sweden         1.000000
Switzerland    1.000000
UK             0.819444
USA            0.000000
Name: STATE, dtype: float64

In [10]:
df['STATE'] = df['STATE'].fillna('Unknown')

In [11]:
print(df.isnull().sum())

ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
STATE                  0
POSTALCODE            76
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [12]:
pd.crosstab(df['COUNTRY'], df['TERRITORY'])

TERRITORY    APAC  EMEA  Japan
COUNTRY
Australia     185     0      0
Austria         0    55      0
Belgium         0    33      0
Denmark         0    63      0
Finland         0    92      0
France          0   314      0
Germany         0    62      0
Ireland         0    16      0
Italy           0   113      0
Japan           0     0     52
Norway          0    85      0
Philippines     0     0     26
Singapore      36     0     43
Spain           0   342      0
Sweden          0    57      0
Switzerland     0    31      0
UK              0   144      0

In [13]:
df[df['COUNTRY'] == 'Singapore']

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
30,10150,45,100.00,8,10993.50,9/19/2003 0:00,Shipped,3,9,2003,...,"Bronz Sok., Bronz Apt. 3/6 Tesvikiye",NaN,Singapore,Unknown,79903,Singapore,Japan,Natividad,Eric,Large
137,10150,20,100.00,1,3191.20,9/19/2003 0:00,Shipped,3,9,2003,...,"Bronz Sok., Bronz Apt. 3/6 Tesvikiye",NaN,Singapore,Unknown,79903,Singapore,Japan,Natividad,Eric,Medium
143,10217,48,100.00,4,7020.48,2/4/2004 0:00,Shipped,1,2,2004,...,Village Close - 106 Linden Road Sandown,2nd Floor,Singapore,Unknown,69045,Singapore,APAC,Victorino,Wendy,Large
146,10259,26,100.00,12,4033.38,6/15/2004 0:00,Shipped,2,6,2004,...,Village Close - 106 Linden Road Sandown,2nd Floor,Singapore,Unknown,69045,Singapore,APAC,Victorino,Wendy,Medium
187,10117,33,100.00,9,6034.38,4/16/2003 0:00,Shipped,2,4,2003,...,"Bronz Sok., Bronz Apt. 3/6 Tesvikiye",NaN,Singapore,Unknown,79903,Singapore,Japan,Natividad,Eric,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2510,10117,38,79.68,6,3027.84,4/16/2003 0:00,Shipped,2,4,2003,...,"Bronz Sok., Bronz Apt. 3/6 Tesvikiye",NaN,Singapore,Unknown,79903,Singapore,Japan,Natividad,Eric,Medium
2618,10150,20,100.00,3,2104.00,9/19/2003 0:00,Shipped,3,9,2003,...,"Bronz Sok., Bronz Apt. 3/6 Tesvikiye",NaN,Singapore,Unknown,79903,Singapore,Japan,Natividad,Eric,Small
2624,10217,31,88.00,6,2728.00,2/4/2004 0:00,Shipped,1,2,2004,...,Village Close - 106 Linden Road Sandown,2nd Floor,Singapore,Unknown,69045,Singapore,APAC,Victorino,Wendy,Small
2718,10117,45,83.42,1,3753.90,4/16/2003 0:00,Shipped,2,4,2003,...,"Bronz Sok., Bronz Apt. 3/6 Tesvikiye",NaN,Singapore,Unknown,79903,Singapore,Japan,Natividad,Eric,Medium
2798,10117,50,43.68,2,2184.00,4/16/2003 0:00,Shipped,2,4,2003,...,"Bronz Sok., Bronz Apt. 3/6 Tesvikiye",NaN,Singapore,Unknown,79903,Singapore,Japan,Natividad,Eric,Small

In [14]:
df[df['TERRITORY'].isnull()] ['COUNTRY'].value_counts()

COUNTRY
USA       1004
Canada      70
Name: count, dtype: int64

In [15]:
pd.crosstab(df['COUNTRY'], df['TERRITORY'], dropna=False)

TERRITORY    APAC  EMEA  Japan   NaN
COUNTRY
Australia     185     0      0     0
Austria         0    55      0     0
Belgium         0    33      0     0
Canada          0     0      0    70
Denmark         0    63      0     0
Finland         0    92      0     0
France          0   314      0     0
Germany         0    62      0     0
Ireland         0    16      0     0
Italy           0   113      0     0
Japan           0     0     52     0
Norway          0    85      0     0
Philippines     0     0     26     0
Singapore      36     0     43     0
Spain           0   342      0     0
Sweden          0    57      0     0
Switzerland     0    31      0     0
UK              0   144      0     0
USA             0     0      0  1004

In [16]:
df.loc[
    (df['COUNTRY'].isin(['USA', 'Canada'])) & 
    (df['TERRITORY'].isna()), 'TERRITORY'] = 'North America'

In [17]:
df[df['COUNTRY'].isin(['USA', 'Canada'])] [['COUNTRY', 'TERRITORY']].head(20)

   COUNTRY      TERRITORY
0      USA  North America
3      USA  North America
4      USA  North America
5      USA  North America
8      USA  North America
11     USA  North America
12     USA  North America
13     USA  North America
15     USA  North America
18     USA  North America
19     USA  North America
23     USA  North America
29     USA  North America
31     USA  North America
33     USA  North America
35  Canada  North America
36     USA  North America
37     USA  North America
38     USA  North America
44     USA  North America

In [18]:
df.loc[
    df['COUNTRY'].isin(['USA', 'Canada']), 'TERRITORY'].isna().sum()

np.int64(0)

In [19]:
df[df['TERRITORY'].isna()] ['COUNTRY'].value_counts()

Series([], Name: count, dtype: int64)

In [20]:
df['TERRITORY'].isna().sum()

np.int64(0)

In [21]:
df[df['COUNTRY'].isin(['USA', 'Canada'])] ['TERRITORY'].value_counts(dropna=False)

TERRITORY
North America    1074
Name: count, dtype: int64

In [22]:
df[df['TERRITORY'].isna()] ['COUNTRY'].value_counts()

Series([], Name: count, dtype: int64)

In [23]:
df['ORDERDATE'] = pd.to_datetime(df['ORDERDATE'])

In [24]:
df['Total_Revenue'] = df['QUANTITYORDERED'] * df['PRICEEACH']

In [25]:
df = df[df['YEAR_ID'] == 2004]

In [26]:
df.rename(columns={'Total_Revenue': 'TOTAL_REVENUE'}, inplace=True)

In [27]:
df.columns

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID',
       'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
       'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE',
       'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME',
       'DEALSIZE', 'TOTAL_REVENUE'],
      dtype='object')

In [28]:
pd.set_option('display.max_columns', None)
df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE,MSRP,PRODUCTCODE,CUSTOMERNAME,PHONE,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,TOTAL_REVENUE
9,10211,41,100.0,14,4708.44,2004-01-15,Shipped,1,1,2004,Motorcycles,95,S10_1678,Auto Canal Petit,(1) 47.55.6555,"25, rue Lauriston",NaN,Paris,Unknown,75016,France,EMEA,Perrier,Dominique,Medium,4100.0
10,10223,37,100.0,1,3965.66,2004-02-20,Shipped,1,2,2004,Motorcycles,95,S10_1678,"Australian Collectors, Co.",03 9520 4555,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,APAC,Ferguson,Peter,Medium,3700.0
11,10237,23,100.0,7,2333.12,2004-04-05,Shipped,2,4,2004,Motorcycles,95,S10_1678,Vitachrome Inc.,2125551500,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,North America,Frick,Michael,Small,2300.0
12,10251,28,100.0,2,3188.64,2004-05-18,Shipped,2,5,2004,Motorcycles,95,S10_1678,Tekni Collectables Inc.,2015559350,7476 Moss Rd.,NaN,Newark,NJ,94019,USA,North America,Brown,William,Medium,2800.0
13,10263,34,100.0,2,3676.76,2004-06-28,Shipped,2,6,2004,Motorcycles,95,S10_1678,Gift Depot Inc.,2035552570,25593 South Bay Ln.,NaN,Bridgewater,CT,97562,USA,North America,King,Julie,Medium,3400.0

#### LOAD

In [34]:
fil_path = "sales.csv"

def Extract():
    df = pd.read_csv(r"C:\Users\hp\Desktop\Datasets\sales.csv")
    return df

def Transform(df):
    df.drop('ADDRESSLINE2',axis = 1, inplace = True)
    df['STATE'] = df['STATE'].fillna('Unknown')
    df.loc[
        (df['COUNTRY'].isin(['USA', 'Canada'])) & 
        (df['TERRITORY'].isna()), 'TERRITORY'] = 'North America'
    df['ORDERDATE'] = pd.to_datetime(df['ORDERDATE'])
    df['Total_Revenue'] = df['QUANTITYORDERED'] * df['PRICEEACH']
    df = df[df['YEAR_ID'] == 2004]
    df.rename(columns={'Total_Revenue': 'TOTAL_REVENUE'}, inplace=True)
    return df


def load(df):
    connection = psycopg2.connect(
    host = "localhost",
    dbname = "Sales ",
    user = "postgres",
    password = "1234"
     
    )
    
    con = connection.cursor()
    
    for _, row in df.iterrows():
        con.execute("""
            INSERT INTO Sales_Record(
            ORDERNUMBER, QUANTITYORDERED, PRICEEACH, ORDERLINENUMBER,
           SALES, ORDERDATE, STATUS, QTR_ID, MONTH_ID, YEAR_ID,
           PRODUCTLINE, MSRP, PRODUCTCODE, CUSTOMERNAME, PHONE,
           ADDRESSLINE1, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY,
           CONTACTLASTNAME, CONTACTFIRSTNAME, DEALSIZE, TOTAL_REVENUE)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (ORDERNUMBER) DO NOTHING """, tuple (row)
           )
        
    connection.commit()
    con.close()
    connection.close()

if __name__ == "__main__":
    try:
        raw_data = Extract()
        clean_data = Transform(raw_data)
        load(clean_data)
    except Exception as e: 
        print(f"Error: {e}")

C:\Users\hp\AppData\Local\Temp\ipykernel_14628\1651861553.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'Total_Revenue': 'TOTAL_REVENUE'}, inplace=True)

In [30]:
print(df.columns.tolist())

['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER', 'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID', 'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE', 'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE', 'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME', 'DEALSIZE', 'TOTAL_REVENUE']